import poisonAnimation from '../images/greenGasAnimation.png'
import healAnimation from '../images/healAnimation.png'
import armorBoost from '../images/armorBoost.png'
import coldAnimation from '../images/slowAnimation.png'
import stunAnimation from '../images/stunAnimation.png'
import warpSpeedAnimation from '../images/warpSpeedAnimation.png'
import damageBoostIcon from '../images/damageBoostIcon.png';
import damageReductionAnimation from '../images/damageReductionAnimation.png';
import armorReductionAnimation from '../images/armorReductionAnimation.png';

export const GAME_EFFECTS = [
  {
    id: 1,
    name: 'poison',
    duration: 4000,
    durationCount: 0,
    color: 'rgba(7, 151, 24, 0.37)',
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 0,
      width: 256,
      height: 256,
      renderWidth: 100,
      renderHeight: 100,
      rowCount: 4,
      columnCount: 4,
      rate: 1,
      startRate: 1,
      xOffset: 0,
      yOffset: 0,
    }
  },
  {
    id: 2,
    name: 'slow',
    duration: 9000,
    durationCount: 0,
    color: 'rgba(142, 194, 215, 0.54)',
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 1,
      width: 177,
      height: 168,
      renderWidth: 150,
      renderHeight: 150,
      rowCount: 5,
      columnCount: 5,
      rate: 0,
      startRate: 0,
      xOffset: 0,
      yOffset: 0,
    }
  },
  {
    id: 3,
    name: 'damageReduction',
    duration: 11000,
    durationCount: 0,
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 2,
      width: 166,
      height: 164,
      renderWidth: 150,
      renderHeight: 150,
      rowCount: 6,
      columnCount: 4,
      rate: 0,
      startRate: 0,
      xOffset: 0,
      yOffset: 0,
    }
  },
  {
    id: 4,
    name: 'stun',
    duration: 3000,
    durationCount: 0,
    color: 'rgba(3, 2, 29, 0.62)',
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 3,
      width: 128,
      height: 128,
      renderWidth: 100,
      renderHeight: 100,
      rowCount: 4,
      columnCount: 3,
      rate: 1,
      startRate: 1,
      xOffset: 0,
      yOffset: -50,
    }
  },
  {
    id: 5,
    name: 'invisible',
    duration: 11000,
    durationCount: 0,
    color: 'rgba(151, 7, 7, 0.37)',
  },
  {
    id: 6,
    name: 'invulnerable',
    duration: 5000,
    durationCount: 0,
    color: 'rgba(144, 7, 151, 0.37)',
  },
  {
    id: 7,
    name: 'heal',
    duration: 4000,
    durationCount: 0,
    color: 'rgba(19, 20, 22, 0.45)',
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 4,
      width: 128,
      height: 128,
      renderWidth: 100,
      renderHeight: 100,
      rowCount: 4,
      columnCount: 6,
      rate: 1,
      startRate: 1,
      xOffset: 0,
      yOffset: 0,
    }
  },
  {
    id: 8,
    name: 'armorBoost',
    duration: 15000,
    durationCount: 0,
    color: 'rgba(7, 33, 151, 0.37)',
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 5,
      width: 100,
      height: 103,
      renderWidth: 30,
      renderHeight: 30,
      rowCount: 1,
      columnCount: 1,
      rate: 1,
      startRate: 1,
      xOffset: 25,
      yOffset: -25,
    }
  },
  {
    id: 9,
    name: 'warpSpeed',
    duration: 8000,
    durationCount: 0,
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 6,
      width: 128,
      height: 64,
      renderWidth: 50,
      renderHeight: 50,
      rowCount: 4,
      columnCount: 2,
      rate: 1,
      startRate: 1,
      xOffset: -30,
      yOffset: 26,
    }
  },
  {
    id: 10,
    name: 'rapidFire',
    duration: 10000,
    durationCount: 0,
  },
  {
    id: 11,
    name: 'damageBoost',
    duration: 15000,
    durationCount: 0,
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 7,
      width: 70,
      height: 70,
      renderWidth: 30,
      renderHeight: 30,
      rowCount: 1,
      columnCount: 1,
      rate: 1,
      startRate: 1,
      xOffset: 25,
      yOffset: -25,
    }
  },
  {
    id: 12,
    name: 'armorReduction',
    duration: 15000,
    durationCount: 0,
    animation: {
      coordinates: {x: 0, y: 0},
      spriteIndex: 8,
      width: 177,
      height: 168,
      renderWidth: 150,
      renderHeight: 150,
      rowCount: 5,
      columnCount: 5,
      rate: 0,
      startRate: 0,
      xOffset: 0,
      yOffset: 0,
    }
  },
]
export const SPRITE_IMAGES = [
  poisonAnimation,
  coldAnimation,
  damageReductionAnimation,
  stunAnimation,
  healAnimation,
  armorBoost,
  warpSpeedAnimation,
  damageBoostIcon,
  armorReductionAnimation,
]
